name: Publish Postgres Acorn image
on:
  push:
      tags:
        - "v*.*.*"

jobs:
  publish:
    name: Publish
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - uses: acorn-io/actions-setup@v2
        with:
          acorn-version: "main"
      - name: Login to GHCR
        uses: acorn-io/actions-login@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build and Publish Acorn image
        run: |
          TAG=${GITHUB_REF#refs/*/}
          acorn build --platform linux/amd64 --push -t ghcr.io/lucj/acorn-postgres:$TAG .